<?php

namespace Tests\Feature;

use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class HelloTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan('migrate');
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function testAccessAddPage()
    {
        $response = $this->get('/thread/add');

        $response->assertStatus(200);
    }

    public function testPostCategory()
    {
        $response = $this->withHeaders([
            'X-Header' => 'Value',
        ])->json('POST', '/thread/add', ['name' => 'Sally', 'temp_name' => 'ms,sally']);

        $response
            ->assertStatus(200);
    }
}
