<?php
/**
 * User: nk_t
 * Date: 2019-07-25
 * Time: 22:10
 */

namespace Tests\Unit;

use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;
use App\Repository\CategoryRepository;

class CategoryRepositoryTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan('migrate:refresh');
    }


    /**
     * A basic test example.
     *
     * @return void
     */
    public function testSave()
    {
        $repository = new CategoryRepository();
        $saved_repo = $repository->save(['name' => 'test', 'temp_name' => 'test_temp_name']);

        $this->assertEquals('test_temp_name', $saved_repo->handleName());

    }
}
